class MsgType:
    GAME_SETTINGS = 1
    INITIALIZE_MAP = 4
    UNKNOWN_6 = 6
    CHOOSE_PLAYER_TO_ROB_KNIGHT = 20  # same prompt as 29, but triggered by playing a knight pre-roll
    DISCARD = 13
    CARD_SELECTION_PROMPT = 18  # dual purpose: monopoly (1 card) or year of plenty (2 cards)
    RESOURCE_DISTRIBUTION = 28
    CHOOSE_PLAYER_TO_ROB = 29
    AVAILABLE_SETTLEMENT_PLACEMENTS = 30
    AVAILABLE_ROAD_PLACEMENTS = 31
    AVAILABLE_ROBBER_PLACEMENTS = 33
    RESOURCE_EXCHANGE = 43
    UNKNOWN_78 = 78
    GAME_STATE_UPDATE = 91


class Action:
    CHAT = 0
    ROLL_DICE = 2
    PLACE_ROBBER = 3
    STEAL_FROM_PLAYER = 5
    END_TURN = 6
    CONFIRM_CARD_SELECTION = 7  # discard, monopoly resource, or year of plenty resources
    UPDATE_DISCARD = 8
    BUY_DEV_CARD = 9
    PLACE_INITIAL_ROAD = 11
    BUILD_ROAD = 12
    PLACE_INITIAL_SETTLEMENT = 15
    BUILD_SETTLEMENT = 16
    UPGRADE_CITY_HIGHLIGHT = 17
    CONFIRM_BUILD_CITY = 18
    BUILD_CITY = 19
    ROAD_BUILDING_SECOND_ROAD = 21
    WRITE_TRADE = 47
    CONFIRM_DEV_CARD = 48
    SEND_TRADE = 49
    RESPOND_TO_TRADE = 50
    FINALIZE_TRADE = 51
    HIGHLIGHT_DEV_CARD = 53
    PAUSE_GAME = 54
    END_GAME = 64