class MsgType:
    GAME_SETTINGS = 1
    INITIALIZE_MAP = 4
    UNKNOWN_6 = 6
    DISCARD = 13
    RESOURCE_DISTRIBUTION = 28
    AVAILABLE_SETTLEMENT_PLACEMENTS = 30
    AVAILABLE_ROAD_PLACEMENTS = 31
    AVAILABLE_ROBBER_PLACEMENTS = 33
    RESOURCE_EXCHANGE = 43
    UNKNOWN_78 = 78
    GAME_STATE_UPDATE = 91


class Action:
    CHAT = 0
    ROLL_DICE = 2
    PLACE_ROBBER = 3
    END_TURN = 6
    CONFIRM_DISCARD = 7
    UPDATE_DISCARD = 8
    BUY_DEV_CARD = 9
    PLACE_INITIAL_ROAD = 11
    BUILD_ROAD = 12
    PLACE_INITIAL_SETTLEMENT = 15
    BUILD_SETTLEMENT = 16
    UPGRADE_CITY_HIGHLIGHT = 17
    CONFIRM_BUILD_CITY = 18
    BUILD_CITY = 19
    ROAD_BUILDING_SECOND_ROAD = 21
    WRITE_TRADE = 47
    CONFIRM_DEV_CARD = 48
    SEND_TRADE = 49
    RESPOND_TO_TRADE = 50
    FINALIZE_TRADE = 51
    HIGHLIGHT_DEV_CARD = 53
    PAUSE_GAME = 54
    END_GAME = 64